### ISSUE TITLE
Server URL Extension is ignored

### ISSUE THREAD

**Issue by syssi** [hellhand/SabdroidEx#1]
I'm trying to setup SabdroidEx without success. My sabnzbd+ daemon is available under https://example.com/nzb/. I use following settings in SabdroidEx:
- Server URL: https://example.com
- Server Port: 443
- Server URL Extension: /nzb/

My apache error.log show something like this:

[01/Jun/2013:18:25:09 +0200] "GET /api?mode=history&output=json&apikey=xxx&ma_username=xxx&ma_password=xxx" 404

It looks like the "Server URL Extension" is not used / ignored.

Kind regards,

Sebastian

**Comment by hellhand** [comment]
Hi,

Thanks for reporting this. This problem has been corrected on the git some time ago.
It was using the same extension as SickBeard for sabnzbd+.

Sadly this was not published on the market in the public version.
The new version will be published shortly with multiple other fixes etc ...

To prevent you from waiting, you can still use the beta version which is updated automatically by Google Play for the members of this community https://plus.google.com/u/0/communities/111434829408878579692 .

It is not the way I would like to do it but there was no tag made regarding the exact revision that was deployed last so I cannot publish a new version with just the corrected code blindly and cannot set the latest version open to everyone as there are some modifications still being tested.

Best regards,
Marc.

**Comment by syssi** [comment]
I joined the community but there is no beta version visible / no update available via google play.

**Comment by hellhand** [comment]
My bad, I forgot to share the registration link in this group.
You should now see a post inviting you to be a beta tester, the application will be updated shortly after that..

Regards.

**Comment by hellhand** [comment]
The version has been publicly published.
