### ISSUE TITLE
History function not working

### ISSUE THREAD

**Issue by Section82** [hellhand/SabdroidEx#2]
Every other feature is working great but for some reason the history function is not working. Nothing gets populated.

Running a nexus 7 android 4.2.2 and sabnzb 0.6.15

**Comment by hellhand** [comment]
Hi,

I know it's stupid but can you try this: 
    - Go to the History tab.
    - Click on the refresh button.
    - Wait 30 seconds.

It can sometimes takes a very long time to retrieve the history
especially if there are many items.

If it does not work, just send me a logcat and I'll check more
specifically if something else is the problem.

**Comment by hellhand** [comment]
As there is no more comment on this I suppose this is working.
