### ISSUE TITLE
Sickbeard: Status update on show, updates season0

### ISSUE THREAD

**Issue by IvoVermeer** [hellhand/SabdroidEx#3]
When I change the status of an episode of a show from 'skipped' to 'wanted', it sets that episode number, but of season 0, to wanted.
This happens for series both with and without a specials-season (season 00).

Debug-log of Sickbeard:
Aug-30 18:04:03 INFO     CP Server Thread-4 :: API :: Starting backlog for Revenge season 0 because some episodes were set to WANTED
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: sickbeard.db: SELECT status FROM tv_episodes WHERE showid = ? AND season = ? with args [248837, 0]
Aug-30 18:04:03 INFO     CP Server Thread-4 :: Seeing if we need any episodes from Revenge season 0
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: sickbeard.db: UPDATE tv_episodes SET status = ?, release_name = ?, file_size = ?, tvdbid = ?, airdate = ?, location = ?, description = ?, hasnfo = ?, hastbn = ?, name = ? WHERE season = ? AND showid = ? AND episode = ? with args [3, '', 0, 4101890, 734391, '', '', False, False, u'Preview', 0, 248837, 1]
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: STATUS IS 3
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: 248837: Saving episode details to database
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: API :: episode.setstatus: curKwargs {'status': u'wanted', 'season': u'0', 'episode': u'1', 'tvdbid': u'248837'}
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: API :: all kwargs: '{'status': u'wanted', 'season': u'0', 'cmd': u'episode.setstatus', 'episode': u'1', 'tvdbid': u'248837'}'
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: API :: all args: '()'
Aug-30 18:04:03 DEBUG    CP Server Thread-4 :: API :: 10.0.0.178 - gave correct API KEY. ACCESS GRANTED
Aug-30 18:04:01 DEBUG    CP Server Thread-9 :: sickbeard.db: SELECT name, episode, airdate, status FROM tv_episodes WHERE showid = ? AND season = ? with args [248837, 1]
Aug-30 18:04:01 DEBUG    CP Server Thread-9 :: API :: show.seasons: curKwargs {'season': u'1', 'tvdbid': u'248837'}
Aug-30 18:04:01 DEBUG    CP Server Thread-9 :: API :: all kwargs: '{'season': u'1', 'cmd': u'show.seasons', 'tvdbid': u'248837'}'
Aug-30 18:04:01 DEBUG    CP Server Thread-9 :: API :: all args: '()'
Aug-30 18:04:01 DEBUG    CP Server Thread-9 :: API :: 10.0.0.178 - gave correct API KEY. ACCESS GRANTED

**Comment by hellhand** [comment]
Hi,

thanks for reporting this, this should be easilly fixed.
I will correct it as soon as I have some time to.

**Comment by hellhand** [comment]
A correction for this has been applied to the new 2.3.8 release.
