### ISSUE TITLE
Unable to remove a string preference

### ISSUE THREAD

**Issue by p3tecracknell** [hellhand/SabdroidEx#4]
First of all, good work with the app, I really like it!
I was wondering if it would be possible to modify SettingsActivity to allow empty strings to update the preference? I was trying to remove the 'Server URL Extension', but as I was setting it to an empty string, it wouldn't update the value.

For anyone else reading this, the work around is to clear all data and re-entering all the values.

**Comment by hellhand** [comment]
This has been changed
